SELECT DEPARTMENT.Dnumber, COUNT(DEPT_LOCATIONS.Dlocation) FROM DEPT_LOCATIONS, DEPARTMENT 
WHERE DEPARTMENT.Dnumber=DEPT_LOCATIONS.Dnumber AND DEPARTMENT.Mgr_ssn IN (     
    SELECT DEPENDENT.Essn FROM DEPARTMENT, DEPENDENT      
    WHERE DEPARTMENT.Mgr_ssn=DEPENDENT.Essn AND DEPENDENT.Sex="F"      
    GROUP BY DEPARTMENT.Mgr_ssn      
    HAVING COUNT(*)>=2) 
GROUP BY DEPARTMENT.Dnumber;