SELECT EMPLOYEE.Fname, EMPLOYEE.Lname, EMPLOYEE.Ssn FROM EMPLOYEE, DEPARTMENT WHERE DEPARTMENT.Mgr_ssn=EMPLOYEE.Ssn AND EMPLOYEE.Dno in 
    (SELECT Dnumber FROM DEPARTMENT, EMPLOYEE HAVING EMPLOYEE.Ssn in                          
        (SELECT Essn FROM WORKS_ON GROUP BY Essn HAVING SUM(Hours)<40));