SELECT DEPARTMENT.Mgr_ssn, COUNT(Pno) FROM DEPARTMENT, WORKS_ON
WHERE DEPARTMENT.Mgr_ssn in (
    SELECT Mgr_ssn FROM DEPARTMENT, PROJECT
    WHERE DEPARTMENT.Dnumber=PROJECT.Dnum AND PROJECT.Pname="ProductY")
AND DEPARTMENT.Mgr_ssn=WORKS_ON.Essn
GROUP BY DEPARTMENT.Mgr_ssn;